### PR TITLE
Support dev & hg sites and show historical data

### PR DESCRIPTION
**Pull request by KwanEsq**
Finally submitting the stuff I mentioned ages ago.

### CODE REVIEW

**Comment by mystor** [comment]
Thanks! :-)

**Comment by mystor** [comment]
Threw this version onto amo: https://addons.mozilla.org/en-CA/firefox/addon/moz-phab-diff-info/

**Comment by KwanEsq** [comment]
Thanks!  Did you set it as public though?  I can't see it :S

**Comment by mystor** [comment]
Apparently it failed addon review. I don't really have any intention to write up a better description for this addon, as it's really intended as a one-off.

image

I'd look into getting the signed extension uploaded as a release, but it appears my current attempt to do so is completely broken. I don't really have time to look into it, but I'll try to do so eventually.

**Comment by mystor** [comment]
Managed to switch it back to a non-public listing after multiple attempts. It's now version 0.2.2: https://github.com/mystor/phab-creationMethod-ext/releases/tag/v0.2.2

**Comment by KwanEsq** [comment]
Thanks!  Bummer about the hoops to jump through for making it public, but seeing as we're the only ones likely to use it not a big deal that it isn't.

**Pull request merged**
